public enum BroadcastCode
{
    //MONO
    MONO_AWAKE,
    MONO_START,
    MONO_ONENABLE,
    MONO_ONDISABLE,
    MONO_ONDESTROY,
    MONO_UPDATE,
    MONO_FIXEDUPDATE,
    MONO_ONAPPLICATIONPAUSE,
    MONO_ONAPPLICATIONFOCUS
}